# CMD python db_migrate.py db init && python db_migrate.py db migrate && python db_migrate.py db upgrade && python app.py

version: "3"
services:
  web:
    build: .
    image: python:2.7
    restart: 'always'
    command: 'python db_migrate.py db init && python db_migrate.py db migrate && python db_migrate.py db upgrade && python app.py'
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:10
    restart: 'always'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'youtube'
    ports:
      - 5432