version: "3"
services:
  web:
    build: .
    image: python:2.7
    restart: 'always'
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:10
    restart: 'always'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'youtube'
    # command: ['psql', '-d', 'youtube', '-U', 'docker', '-f', 'init.sql']
    ports:
      - "2345:5432"